.TH griffith 1 "Aug 28, 2005"  
.SH NAME
griffith \- film collection manager
.SH SYNOPSIS
\fBgriffith\fR [OPTIONS]
.SH DESCRIPTION
Griffith is a film collection manager.
Adding items to the movie collection is as quick and easy as typing the film
title and selecting a supported source. Griffith will then try to fetch all
the related information from the Web.
.SH OPTIONS
.TP 
\fB\-h\fR, \fB\-\-help\fR 
Show usage information.
.TP 
\fB\-d\fR, \fB\-\-debug\fR 
Run in debug mode.
.SH "SEE ALSO"
Homepage: http://griffith.vasconunes.net/
.PP
\fBgriffith\-export\-template\fR(5)
.SH BUGS
If you want to help or report any bugs founded please visit
homepage or
http://forge.novell.com/modules/xfmod/tracker/?group_id=1689&atid=2757
.SH AUTHORS
griffith was initially written by Vasco Nunes. See the AUTHORS file
for a list of other contributors.
.PP
Copyright (C) 2005 Vasco Nunes vasco.m.nunes@gmail.com
.PP
This man page was written by Piotr Ozarowski
