.TH griffith 1 "Dec 20, 2006"  
.SH NAME
griffith \- film collection manager
.SH SYNOPSIS
\fBgriffith\fR [OPTIONS]
.SH DESCRIPTION
Griffith is a film collection manager.
Adding items to the movie collection is as quick and easy as typing the film
title and selecting a supported source. Griffith will then try to fetch all
the related information from the Web.
.SH OPTIONS
.TP 
\fB\-h\fR \fB\-\-help\fR 
Show usage information.
.TP 
\fB\-D\fR \fB\-\-debug\fR 
Run in debug mode.
.TP 
\fB\-C\fR \fB\-\-clean\fR 
find and delete orphan files in posters directory.
.TP 
\fB\-\-check\-dep\fR 
check dependencies \- if all needed Python modules are installed, it prints nothting.
.TP 
\fB\-\-sqlecho\fR 
Prints all SQL queries to standart output.
.TP 
\fB\-\-home DIR\fR 
Set Griffith's home directory. Use this option if you want to change the default ~/.griffith
.PP
Printing movie list:
.TP 
\fB\-c <expr>\fR \fB\-\-cast=<expr>\fR 
cast field must contain <expr>
.TP 
\fB\-d <expr>\fR \fB\-\-director=<expr>\fR 
director field must contain <expr>
.TP 
\fB\-o <expr>\fR \fB\-\-original_title=<expr>\fR 
original title field must contain <expr>
.TP 
\fB\-t <expr>\fR \fB\-\-title=<expr>\fR 
title field must contain <expr>
.TP 
\fB\-y <number>\fR \fB\-\-year=<number>\fR 
movie must be released in year <number>
.TP 
\fB\-s <columns>\fR \fB\-\-sort=<columns>\fR 
set sort columns to <columns>. Example: \-\-sort=o_title,number,director
.SH "SEE ALSO"
Homepage: http://www.griffith.cc/
.SH BUGS
If you want to help or report any bugs founded please visit
homepage or
https://bugs.launchpad.net/griffith
.SH AUTHORS
Griffith was written by Vasco Nunes and Piotr O\(oA\(14arowski.
See the AUTHORS and THANKS files for a list of other
contributors.
.PP
Copyright (C) 2005\-2008 Vasco Nunes vasco.m.nunes@gmail.com,
Piotr O\(oA\(14arowski ozarow+griffith@gmail.com,
.PP
This man page was written by Piotr Ozarowski
