#!/bin/sh
# TODO: remove this file after releasing Squeeze
set -e
if [ "$1" = upgrade ]
then
   if dpkg --compare-versions "$2" lt 0.9.10-1 ||
     (dpkg --compare-versions "$2" gt 0.10~ && 
      dpkg --compare-versions "$2" lt 0.10~beta3-1~)
   then
	pycentral pkgremove griffith || true
	rm -rf /usr/share/griffith/lib
   fi
fi

#DEBHELPER#
