'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH griffith 1 "Aug 28, 2005" "" ""
.SH NAME
griffith \- gestor de colec\(,c\(~oes de filmes
.SH SYNOPSIS
'nh
.fi
.ad l
\fBgriffith\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRI\(,C\(~AO
Griffith \('e um gestor de colec\(,c\(~oes de filmes.
Adicionar novos filmes \(`a colec\(,c\(~ao \('e t\(~ao simples como escrever o nome ou parte
do nome do t\('itulo do filme e seleccionar a origem dos dados. Griffith ir\('a tentar
obter os dados acerca do filme a partir da internet.
.SH OP\(,C\(~OES
.TP 
\*(T<\fB\-h\fR\*(T>, \*(T<\fB\-\-help\fR\*(T> 
Mostra instru\(,c\(~oes de utiliza\(,c\(~ao.
.TP 
\*(T<\fB\-d\fR\*(T>, \*(T<\fB\-\-debug\fR\*(T> 
Corre em modo de depura\(,c\(~ao.
.SH "VEJA TAMB\('EM"
Homepage: \(lahttp://griffith.vasconunes.net/\(ra
.SH BUGS
Se desejar ajudar ou comunicar quaisquer erros ou bug por favor visite a p\('agina oficial do projecto em
.URL http://griffith.vasconunes.net/ homepage
ou
\(lahttp://forge.novell.com/modules/xfmod/tracker/?group_id=1689&atid=2757\(ra
.SH AUTORES
\fBgriffith\fR foi inicialmente escrito por Vasco Nunes. Veja o ficheiro AUTHORS para uma listagem completa de outros colaboradores do projecto.
.PP
Copyright (C) 2005 Vasco Nunes <\*(T<vasco.m.nunes@gmail.com\*(T>>
.PP
Esta p\('agina do manual foi escrita por Piotr Ozarowski
