.TH griffith 1 "Aug 28, 2005"  
.SH NAME
griffith \- gestor de colec\(,c\(~oes de filmes
.SH SYNOPSIS
\fBgriffith\fR [OPTIONS]
.SH DESCRI\(,C\(~AO
Griffith \('e um gestor de colec\(,c\(~oes de filmes.
Adicionar novos filmes \(`a colec\(,c\(~ao \('e t\(~ao simples como escrever o nome ou parte
do nome do t\('itulo do filme e seleccionar a origem dos dados. Griffith ir\('a tentar
obter os dados acerca do filme a partir da internet.
.SH OP\(,C\(~OES
.TP 
\fB\-h\fR, \fB\-\-help\fR 
Mostra instru\(,c\(~oes de utiliza\(,c\(~ao.
.TP 
\fB\-d\fR, \fB\-\-debug\fR 
Corre em modo de depura\(,c\(~ao.
.SH "VEJA TAMB\('EM"
Homepage: http://griffith.vasconunes.net/
.PP
\fBgriffith\-export\-template\fR(5)
.SH BUGS
Se desejar ajudar ou comunicar quaisquer erros ou bug por favor visite a p\('agina oficial do projecto em
homepage ou
http://forge.novell.com/modules/xfmod/tracker/?group_id=1689&atid=2757
.SH AUTORES
griffith foi inicialmente escrito por Vasco Nunes. Veja o ficheiro AUTHORS para uma listagem completa de outros colaboradores do projecto.
.PP
Copyright (C) 2005 Vasco Nunes vasco.m.nunes@gmail.com
.PP
Esta p\('agina do manual foi escrita por Piotr Ozarowski
