.TH griffith 1 "Aug 28, 2005"  
.SH NAME
griffith \- zarz\(+-dca kolekcji film\('ow
.SH SYNOPSIS
\fBgriffith\fR [OPCJE]
.SH OPIS
Griffith zarz\(+-dza kolekcj\(+- film\('ow.
Dodawanie kolejnych pozycji jest tak \(S3atwe i szybkie, jak wpisanie tytu\(S3u filmu i wybranie
odpowiedniego \(14r\('od\(S3a. Griffith nast\(^epnie sam pobierze z internetu potrzebne informacje.
.SH OPCJE
.TP 
\fB\-h\fR, \fB\-\-help\fR 
Pokazuje informacje o sposobie u\(r?ycia.
.TP 
\fB\-d\fR, \fB\-\-debug\fR 
Uruchamia program w trybie debugowania.
.SH "ZOBACZ TAK\(a-E"
Strona domowa: http://griffith.vasconunes.net/
.PP
\fBgriffith\-export\-template\fR(5)
.SH B\(Po\(^EDY
Je\(r?eli szukasz pomocy lub chcesz zg\(S3osi\(ae b\(S3\(+-d, odwied\(14
stron\(^e domow\(+- lub
http://forge.novell.com/modules/xfmod/tracker/?group_id=1689&atid=2757
.SH AUTORZY
griffith zosta\(S3 napisany przez Vasco Nunesa. Zobacz plik AUTHORS z list\(+- wsp\('o\(S3pracownik\('ow
.PP
Copyright (C) 2005 Vasco Nunes vasco.m.nunes@gmail.com
.PP
Ta strona podr\(^ecznika zosta\(S3a napisana przez Piotra O\(r?arowskiego
